### ISSUE TITLE
This is great, I'd like to help and contribute

### ISSUE THREAD

**Issue by IjzerenHein** [release-notes/release-notes#1]
Dear Alrik,

I stumbled upon your release-notes project on Github by accident. I really like what you are trying to achieve here and fully support this initiative. I myself was actually looking for tools and thinking of writing some scripts to automate release-notes management for my react-native project. One of the goals I have there is that I want to manage my release notes in a human readable file, and yaml seems like a great fit. And then I want to be able to convert that file into a JSON file so I can include it in my react-native project. This seems quite trivial, but one of the challenges I face
is that I want to be able to generate two different JSON files, one for iOS and one for Android (sometimes bugs are fixed for specific platforms only). So I'd need to do some filtering on that.

Anyways, what I guess that I'm trying to say is, I'd like to help out, either by building tools or/and testing and verifying the ideas you propose.

best regards, Hein

**Comment by alrik** [comment]
Wow Hein, thank you for your support offering.
I'd be more than happy about any feedback, idea or PR,
so yes, let's discuss how you could contribute to release-notes :)

I'm currently implementing the last features for the alpha release of the hub, a web repository for release-notes, where customers or dependents can subscribe to release notes updates.

Once I deployed this, I'll definately ask for feedback.
I did not expact such an early support offering, that's why there is no backlog of defined user stories, yet.
I guess it's a good time to set this up now :)


But let's talk a bit more about your use case.
The json files you want to generate from `release-notes.yml` are they unique to your particular project, or are they common android/iOS changelog files?
_(I'm not into mobile app development, so i do not know how release notes are handled with app releases.)_

I think it could be a cool feature to add support for flexible tagging of release note modifications. A post-processor/converter could then consider these tags, eg. by excluding specific entries from being written to a JSON file.

Something like:

```yml
title: How Tagging may look like
description: >
  In order to give more context to a stated modification we could introduce
  some kind of optional changeset tagging.

releases:
  - version: Unreleased
    improved:
      - title: Adjust submit button color. 
        tags:
          - Android
          - UX
    fixed:
      - title: Fix some crash.
        tags:
          - iOS
    added:
      - Some fancy new feature. 
```

What do you think in general about this feature? Would that be helpful for your use case?

I already have another converter in my mind that will produce a CHANGELOG.md file from _release notes_ according to this [changelog recommendation](http://keepachangelog.com/en/1.0.0/). 
My plan was to define a converter interface and add support for invoking converters from the release notes cli tool like: `release-notes convert --type changelog` or something similar.
For sure there will be project specific converters as well. So i might be a cool feature to support conversion with a given node-module _(implementing the converter interface)_

```js
npm i -g @my-org/my-custom-converter
release-notes convert --converter-module @my-org/my-custom-converter
``` 

I hope i did not overwhelm you with my ideas :)

Thank you again and I'm looking forward to hearing back from you.

Best,
Alrik
